# Generated by Django 3.2.16 on 2023-12-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date_created',)},
        ),
    ]
