# Generated by Django 3.2.16 on 2023-10-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='descrption',
        ),
    ]
