# Generated by Django 3.2.16 on 2023-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231003_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descrption',
            field=models.TextField(max_length=255),
        ),
    ]
