# Generated by Django 3.2.16 on 2023-10-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrption',
            new_name='description',
        ),
    ]
